Updated tool script order and functions

diff --git a/slackdoctool b/slackdoctool
--- a/slackdoctool
+++ b/slackdoctool
@@ -68,6 +68,72 @@ SCSTXT=$(tput setaf 2)
 #REVERSE=$(tput smso)
 #UNDERLINE=$(tput smul)
 
+IsRoot() {
+  # Check if the script is run as root
+  if [ "$(id -u)" = "0" ]; then
+     PrintError "Do not run the script as root."
+     exit 1
+  fi
+}
+
+CheckUpdate() {
+# Checks githhub for a new version of the file and downloads it
+
+  NEW_VERSION=$(lynx -dump ${VERSION_URL} | grep slackdoctool | cut -d "=" -f
+2)
+  printf "\n${BLDTXT}%s${NRMTXT}\n" \
+    "Checking for an updated script."
+  if [ "${NEW_VERSION}" = "${VERSION}" ]; then
+    printf "\n${SCSTXT}%s${NRMTXT}\n" \
+      "Your copy is up to date"
+  else 
+    printf "\n${BLDTXT}%s${NRMTXT}\n" \
+      "A new version is available."
+    read -p "Would you like to fetch version ${NEW_VERSION} [y/N]? " yn
+    case ${yn} in
+    [Yy*]* )
+      wget ${SCRIPT_URL} --output-document=${TMP_DIR}/slackdoctool
+      if [ "$?" = "0" ]; then
+#SCSTXT=$(tput setaf 153)
+        printf "\n${SCSTXT}%s${NRMTXT}\n" \
+          "Version ${VERSION} has been saved to ${TMP_DIR}/slackdoctool."
+      else
+        printf "\n${ERRTXT}%s${NRMTXT}\n" \
+          "The update failed, try again later."
+      fi
+      ;;
+    * )
+      printf "\n${ERRTXT}%s${NRMTXT}\n" \
+        "Download Declined, terminating action."
+      ;;
+    esac
+  fi
+}
+
+BuildStructure() 
+{
+  # Accepts no arguments, builds directory structure
+
+  if [ ! -d ${TEMPLATE_DIR} ]; then
+    PrintText 0 "${ERRTXT}" "The user directory at ${SD_DIR} \
+      does not exist" 1
+    read -p "Would you like to create it? (Y/N) :" yn
+    case ${yn} in
+      [Yy*]* )
+        mkdir -v ${SD_DIR}
+        if [ ! -d ${TEMPLATE_DIR} ]; then
+          mkdir -v ${TEMPLATE_DIR}
+        fi
+        ;;
+      * )
+        PrintError "Cannot resume without directory in place, Terminating."
+        exit 1
+        ;;
+    esac
+  fi
+}
+
+
 PrintText() {
   # Used to output properly wrapping text with indentation and formatting.
 
@@ -139,12 +205,302 @@ HelpArg() {
 
 }
 
-IsRoot() {
-  # Check if the script is run as root
-  if [ "$(id -u)" = "0" ]; then
-     PrintError "Do not run the script as root."
-     exit 1
+RefreshTemplates() {
+  # Refresh the list of available templates
+  
+  PrintText 2 "${BLDTXT}"  "Refreshing the list of available templates..." 1
+  lynx -dump ${TEMP_URL} | awk -F: '/templates:/ {print $NF}'>${TEMP_FILE}
+  
+  # Make the order of the templates more structured
+  sort ${TEMP_FILE} -o ${TEMP_FILE}
+
+  # Populates the TEMPS array with a list of available templates
+  SetTemps
+}
+
+SetTemps() {
+  # Sets an array with the contents of the template index 
+  TEMPS=()
+  while read line; do
+    TEMPS+=("${line}")
+  done < ${TEMP_FILE}
+}
+
+# 
+
+AvailableTemplates() {
+  # Displays a list of available templates and usage
+  # Make sure the template file exists and the TEMPS array is set
+  if [ ! -f "${TEMP_FILE}" ]; then
+    RefreshTemplates
+  else
+    SetTemps
   fi
+
+  PrintText 0 "${BLDTXT}" "The following templates are available:" 1
+  
+  # Loop over the TEMPS array to display available templates 
+  for i in ${!TEMPS[*]}
+  do
+    printf "%4d: %s\n" $i ${TEMPS[$i]}
+  done
+  printf "\n"
+}
+
+PullTemplates() {
+  # Pulls the listed template files into the templates directory
+
+  # Checks if the templte directory exists
+  if [ ! -f "${TEMP_FILE}" ]; then
+    RefreshTemplates
+  else
+    SetTemps
+  fi
+
+  # Pulls the templates listed in the TEMPS array.
+  for TEMPLATE in "${TEMPS[@]}"
+  do
+    PullPage "templates:${TEMPLATE}" "${TEMPLATE_DIR}"
+  done
+  PrintText 2 "${SCSTXT}" "All templates have been successfully retrieved." 1
+}
+
+PullPage() {
+  # Pulls the single page from $1 into the location at $2
+
+  local EXTRACTLINE="?do=export_raw"
+
+  # Page holds the name of the requested page
+  local PAGE=${1}
+
+  # If destination does not include ending slash add it
+  if [[ ${2} == *"/" ]]; then
+    local DESTDIR="${2}"
+  else
+    local DESTDIR="${2}/"
+  fi
+  
+
+  if [ ! -d ${DESTDIR} ]; then
+    PrintText 2 "${ERRTXT}" "The ${DESTDIR} directory does not exist,
+terminating action" 1
+    exit 1
+  fi
+
+  # if requested page includs base url remove it so output page can be 
+  #  determined
+  if [[ "${PAGE}" == *"${SD_URL}"* ]]; then
+    local PAGE="$(echo "${PAGE}"|cut -d "/" -f 4)"
+  fi
+
+  # Set output file name
+  if [ "${2}" = "${TEMPLATE_DIR}" ]; then
+    local OF="$(echo "${PAGE}"|sed 's/:/-/g'|sed 's/templates-//g').${EXTENSION}"
+  else
+    local OF="$(echo "${PAGE}"|sed 's/:/-/g').${EXTENSION}"
+  fi
+
+  # If output file exists remove it
+  if [ -e ${DESTDIR}${OF} ]; then
+    rm ${DESTDIR}${OF}
+  fi
+
+  # Append the base url to the page address
+  local PAGE=${SD_URL}/${PAGE}
+
+  if [ -e ${DESTDIR}${OF} ]; then
+    printf "\n${ERRTXT}%s${NRMTXT}\n" "${DESTDIR}${OF} exists"
+    read -p "Would you like to overwrite it? " yn
+    case ${yn} in
+    [Yy]* )
+
+      rm ${DESTDIR}${OF}
+
+      FinishPull ${PAGE}${EXTRACTLINE} ${PAGE} ${DESTDIR}${OF}
+      ;;
+    * )
+      printf ""
+      ;;
+    esac
+  else
+    FinishPull ${PAGE}${EXTRACTLINE} ${PAGE} ${DESTDIR}${OF}
+  fi
+}
+
+FinishPull() {
+  # retrieve the page
+  #
+  # Arg1 = URL
+  # Arg2 = Descriptive Name
+  # Arg3 = Output File Name
+  
+  F_STATUS=""
+  local URL=${1}
+  local DESCRIPT=${2}
+  local OUTFILE=${3}
+  
+  local FAILTEXT="epub_LoadScript"
+
+  wget ${URL} --output-document=${OUTFILE}
+
+  # Test for a valid pull and display associated message
+  if [ -n "$(cat ${OUTFILE}|grep ${FAILTEXT})" ]; then
+    rm ${OUTFILE}
+    PrintText 2 "${ERRTXT}" "${DESCRIPT} does not exist" 1
+  unset F_STATUS
+  else
+    PrintText 2 "${SCSTXT}" "${OUTFILE} is ready to edit" 1
+  F_STATUS=0
+  fi
+}
+
+PullFromList() {
+  # This function is intended to allow a user to specificy a text file
+  #  list of pages to retreive and pull them into the desired directory
+  #
+  # Arg1 = List File
+  # Arg2 = Destination Dir
+
+  local LISTFILE=${1}
+  local DESTDIR=${2}
+  FETCHED=()
+  FAILED=()
+  
+  while read PAG
+  do
+    PullPage "${PAG}" "${DESTDIR}" 
+    [ -z "${F_STATUS}" ] && FAILED+=("${PAG}") || FETCHED+=("${PAG}")
+  done < ${LISTFILE}
+  echo
+  echo "Fetched ${#FETCHED[@]} document(s): ${FETCHED[@]}"
+  echo "Failed to fetch ${#FAILED[@]} document(s): ${FAILED[@]}"
+  echo
+}
+
+CreateNew() {
+  # Copies a template into a new filename and sets it for editing
+
+  # Pull the templates if they are not present
+  if [ ! -d ${TEMPLATE_DIR} ]; then
+    PullTemplates
+  fi
+  
+  TEMPLATE_FILE=${TEMPLATE_DIR}/${TEMPS[${USETEMPLATE}]}.${EXTENSION}
+  OUTPUT_FILE=${SD_DIR}/${NEWFILE}.${EXTENSION}
+
+  if [ -f ${TEMPLATE_FILE} ]; then
+
+    # Check if the output file already exists. If so, edit it.
+    if [ -f ${OUTPUT_FILE} ]; then
+      vim ${OUTPUT_FILE}
+
+      # If the output file does not exist, copy the template, rename and
+      # edit it.
+    else
+      cp ${TEMPLATE_FILE} ${OUTPUT_FILE} && vim ${OUTPUT_FILE}
+    fi
+  else
+    PrintError "There have been problems accessing the template"
+    PrintError "Please, list and/or refresh the templates with -r option"
+    exit 1
+  fi
+}
+
+CopyToClipboard()
+{
+  # Copies a file to the clipboard for pasteing online
+  #
+  # Arg1 = File Name
+  # Arg2 = 1 to turn confirmations ON, else confirmations OFF
+
+  local FILENAME=${1}
+  local CONFS=${2}
+
+
+  ls /var/log/packages | grep "\<xclip\>" > /dev/null
+  if [ ! $? -eq 0 ]; then
+    printf "\n${ERRTXT}%s${NRMTXT}\n" \
+      "xclip is not installed, the contents will need to be manually copied."
+    return 1
+  fi
+
+  if [ -f ${FILENAME} ]
+  then
+    if [ "${CONFS}" = "1" ]
+    then
+      # if xclip is installed on the system, 
+      # copy the contents of the file to clipboard
+      read -p "Would you like the contents of ${FILENAME} to be copied to the
+clipboard [y/N]? " yn
+      case ${yn} in
+      [Yy*]* )
+        cat ${FILENAME} | xclip -selection clipboard
+        printf "\n${SCSTXT}%s${NRMTXT}\n" \
+          "The contents of ${FILENAME} has been copied to clipboard."
+        return 1
+        ;;
+      esac
+    else
+      cat ${FILENAME} | xclip -selection clipboard
+    fi
+  else
+    printf "\n${ERRTXT}%s${NRMTXT}\n" \
+      "The File ${FILENAME} does not exist, terminating action."
+    exit 1
+  fi
+}
+
+GetSyntaxExample () {
+      PullPage "wiki:syntax" ${SD_DIR}
+      PrintText 0 "" "" 1
+      PrintText 0 "${NRMTXT}" "The example syntax file is now located at
+${SD_DIR}/wiki-syntax.${EXTENSION}" 1
+}
+
+PrepSyntax() {
+  case "${SYNAPP}" in
+    vim)
+      VImSyntax
+      ;;
+    kate)
+      KateSyntax
+      ;;
+    *)
+      PrintError "Cannot set syntax info for ${SYNAPP}, please contact the
+authors of slackdoctool if you want it included."
+      exit 1
+      ;;
+  esac
+}
+
+VimSyntax() {
+  # Update/ Appends the necessary directive to the users .vimrc
+  #  file to set syntax highlighting for slackdocs
+
+  local VIMRC="${HOME}/.vimrc"
+
+  wget ${SYNTAX_URL}/${SYNF_VIM} --output-document=${SD_DIR}/.${SYNF_VIM}
+
+  # removes existing slackdoc syntax template lines if they exist
+  sed -i /${FILETYPE}/d ${VIMRC}
+
+  # Write the new lines to the vimrc file
+  echo "\" Add a pointer to the ${FILETYPE} vim syntax file">>${VIMRC}
+  echo "au BufRead,BufNewFile *.${EXTENSION} set
+filetype=${FILETYPE}">>${VIMRC}
+  echo "au! Syntax ${FILETYPE} source ${SD_DIR}/.${SYNF_VIM}">>${VIMRC}
+
+  PrintText 2 "${SCSTXT}" "The script has added the following lines to your
+vimrc file" 1
+  cat ${VIMRC} | grep ${FILETYPE}
+  printf "\n"
+}
+
+KateSyntax() {
+  PrintText 2 "${BLDTXT}" \
+          "To implement syntax highlighting to slackdoc articles in kate you
+need to enable the MediaWiki syntax highlighting by going to Tools ->
+Highlighting -> Markup -> Mediawiki." 1
 }
 
 DisplayHelp() {
@@ -327,328 +683,6 @@ CheckValid() {
   fi
 }
 
-BuildStructure() 
-{
-  # Accepts no arguments, builds directory structure
-
-  if [ ! -d ${TEMPLATE_DIR} ]; then
-    PrintText 0 "${ERRTXT}" "The user directory at ${SD_DIR} \
-      does not exist" 1
-    read -p "Would you like to create it? (Y/N) :" yn
-    case ${yn} in
-      [Yy*]* )
-        mkdir -v ${SD_DIR}
-        if [ ! -d ${TEMPLATE_DIR} ]; then
-          mkdir -v ${TEMPLATE_DIR}
-        fi
-        ;;
-      * )
-        PrintError "Cannot resume without directory in place, Terminating."
-        exit 1
-        ;;
-    esac
-  fi
-}
-
-
-RefreshTemplates() {
-  # Refresh the list of available templates
-  
-  PrintText 2 "${BLDTXT}"  "Refreshing the list of available templates..." 1
-  lynx -dump ${TEMP_URL} | awk -F: '/templates:/ {print $NF}'>${TEMP_FILE}
-  
-  # Make the order of the templates more structured
-  sort ${TEMP_FILE} -o ${TEMP_FILE}
-
-  # Populates the TEMPS array with a list of available templates
-  SetTemps
-}
-
-SetTemps() {
-  # Sets an array with the contents of the template index 
-  TEMPS=()
-  while read line; do
-    TEMPS+=("${line}")
-  done < ${TEMP_FILE}
-}
-
-# 
-
-AvailableTemplates() {
-  # Displays a list of available templates and usage
-  # Make sure the template file exists and the TEMPS array is set
-  if [ ! -f "${TEMP_FILE}" ]; then
-    RefreshTemplates
-  else
-    SetTemps
-  fi
-
-  PrintText 0 "${BLDTXT}" "The following templates are available:" 1
-  
-  # Loop over the TEMPS array to display available templates 
-  for i in ${!TEMPS[*]}
-  do
-    printf "%4d: %s\n" $i ${TEMPS[$i]}
-  done
-  printf "\n"
-}
-
-PullTemplates() {
-  # Pulls the listed template files into the templates directory
-
-  # Checks if the templte directory exists
-  if [ ! -f "${TEMP_FILE}" ]; then
-    RefreshTemplates
-  else
-    SetTemps
-  fi
-
-  # Pulls the templates listed in the TEMPS array.
-  for TEMPLATE in "${TEMPS[@]}"
-  do
-    PullPage "templates:${TEMPLATE}" "${TEMPLATE_DIR}"
-  done
-  PrintText 2 "${SCSTXT}" "All templates have been successfully retrieved." 1
-}
-
-PullPage() {
-  # Pulls the single page from $1 into the location at $2
-
-  local EXTRACTLINE="?do=export_raw"
-
-  # Page holds the name of the requested page
-  local PAGE=${1}
-
-  # If destination does not include ending slash add it
-  if [[ ${2} == *"/" ]]; then
-    local DESTDIR="${2}"
-  else
-    local DESTDIR="${2}/"
-  fi
-  
-
-  if [ ! -d ${DESTDIR} ]; then
-    PrintText 2 "${ERRTXT}" "The ${DESTDIR} directory does not exist,
-terminating action" 1
-    exit 1
-  fi
-
-  # if requested page includs base url remove it so output page can be 
-  #  determined
-  if [[ "${PAGE}" == *"${SD_URL}"* ]]; then
-    local PAGE="$(echo "${PAGE}"|cut -d "/" -f 4)"
-  fi
-
-  # Set output file name
-  if [ "${2}" = "${TEMPLATE_DIR}" ]; then
-    local OF="$(echo "${PAGE}"|sed 's/:/-/g'|sed 's/templates-//g').${EXTENSION}"
-  else
-    local OF="$(echo "${PAGE}"|sed 's/:/-/g').${EXTENSION}"
-  fi
-
-  # If output file exists remove it
-  if [ -e ${DESTDIR}${OF} ]; then
-    rm ${DESTDIR}${OF}
-  fi
-
-  # Append the base url to the page address
-  local PAGE=${SD_URL}/${PAGE}
-
-  if [ -e ${DESTDIR}${OF} ]; then
-    printf "\n${ERRTXT}%s${NRMTXT}\n" "${DESTDIR}${OF} exists"
-    read -p "Would you like to overwrite it? " yn
-    case ${yn} in
-    [Yy]* )
-
-      rm ${DESTDIR}${OF}
-
-      FinishPull ${PAGE}${EXTRACTLINE} ${PAGE} ${DESTDIR}${OF}
-      ;;
-    * )
-      printf ""
-      ;;
-    esac
-  else
-    FinishPull ${PAGE}${EXTRACTLINE} ${PAGE} ${DESTDIR}${OF}
-  fi
-}
-
-FinishPull() {
-  # retrieve the page
-  #
-  # Arg1 = URL
-  # Arg2 = Descriptive Name
-  # Arg3 = Output File Name
-  
-  F_STATUS=""
-  local URL=${1}
-  local DESCRIPT=${2}
-  local OUTFILE=${3}
-  
-  local FAILTEXT="epub_LoadScript"
-
-  wget ${URL} --output-document=${OUTFILE}
-
-  # Test for a valid pull and display associated message
-  if [ -n "$(cat ${OUTFILE}|grep ${FAILTEXT})" ]; then
-    rm ${OUTFILE}
-    PrintText 2 "${ERRTXT}" "${DESCRIPT} does not exist" 1
-  unset F_STATUS
-  else
-    PrintText 2 "${SCSTXT}" "${OUTFILE} is ready to edit" 1
-  F_STATUS=0
-  fi
-}
-
-PullFromList() {
-  # This function is intended to allow a user to specificy a text file
-  #  list of pages to retreive and pull them into the desired directory
-  #
-  # Arg1 = List File
-  # Arg2 = Destination Dir
-
-  local LISTFILE=${1}
-  local DESTDIR=${2}
-  FETCHED=()
-  FAILED=()
-  
-  while read PAG
-  do
-    PullPage "${PAG}" "${DESTDIR}" 
-    [ -z "${F_STATUS}" ] && FAILED+=("${PAG}") || FETCHED+=("${PAG}")
-  done < ${LISTFILE}
-  echo
-  echo "Fetched ${#FETCHED[@]} document(s): ${FETCHED[@]}"
-  echo "Failed to fetch ${#FAILED[@]} document(s): ${FAILED[@]}"
-  echo
-}
-
-GetSyntaxExample () {
-      PullPage "wiki:syntax" ${SD_DIR}
-      PrintText 0 "" "" 1
-      PrintText 0 "${NRMTXT}" "The example syntax file is now located at
-${SD_DIR}/wiki-syntax.${EXTENSION}" 1
-}
-
-CopyToClipboard()
-{
-  # Copies a file to the clipboard for pasteing online
-  #
-  # Arg1 = File Name
-  # Arg2 = 1 to turn confirmations ON, else confirmations OFF
-
-  local FILENAME=${1}
-  local CONFS=${2}
-
-
-  ls /var/log/packages | grep "\<xclip\>" > /dev/null
-  if [ ! $? -eq 0 ]; then
-    printf "\n${ERRTXT}%s${NRMTXT}\n" \
-      "xclip is not installed, the contents will need to be manually copied."
-    return 1
-  fi
-
-  if [ -f ${FILENAME} ]
-  then
-    if [ "${CONFS}" = "1" ]
-    then
-      # if xclip is installed on the system, 
-      # copy the contents of the file to clipboard
-      read -p "Would you like the contents of ${FILENAME} to be copied to the
-clipboard [y/N]? " yn
-      case ${yn} in
-      [Yy*]* )
-        cat ${FILENAME} | xclip -selection clipboard
-        printf "\n${SCSTXT}%s${NRMTXT}\n" \
-          "The contents of ${FILENAME} has been copied to clipboard."
-        return 1
-        ;;
-      esac
-    else
-      cat ${FILENAME} | xclip -selection clipboard
-    fi
-  else
-    printf "\n${ERRTXT}%s${NRMTXT}\n" \
-      "The File ${FILENAME} does not exist, terminating action."
-    exit 1
-  fi
-}
-
-CreateNew() {
-  # Copies a template into a new filename and sets it for editing
-
-  # Pull the templates if they are not present
-  if [ ! -d ${TEMPLATE_DIR} ]; then
-    PullTemplates
-  fi
-  
-  TEMPLATE_FILE=${TEMPLATE_DIR}/${TEMPS[${USETEMPLATE}]}.${EXTENSION}
-  OUTPUT_FILE=${SD_DIR}/${NEWFILE}.${EXTENSION}
-
-  if [ -f ${TEMPLATE_FILE} ]; then
-
-    # Check if the output file already exists. If so, edit it.
-    if [ -f ${OUTPUT_FILE} ]; then
-      vim ${OUTPUT_FILE}
-
-      # If the output file does not exist, copy the template, rename and
-      # edit it.
-    else
-      cp ${TEMPLATE_FILE} ${OUTPUT_FILE} && vim ${OUTPUT_FILE}
-    fi
-  else
-    PrintError "There have been problems accessing the template"
-    PrintError "Please, list and/or refresh the templates with -r option"
-    exit 1
-  fi
-}
-
-PrepSyntax() {
-  case "${SYNAPP}" in
-    vim)
-      VImSyntax
-      ;;
-    kate)
-      KateSyntax
-      ;;
-    *)
-      PrintError "Cannot set syntax info for ${SYNAPP}, please contact the
-authors of slackdoctool if you want it included."
-      exit 1
-      ;;
-  esac
-}
-
-VimSyntax() {
-  # Update/ Appends the necessary directive to the users .vimrc
-  #  file to set syntax highlighting for slackdocs
-
-  local VIMRC="${HOME}/.vimrc"
-
-  wget ${SYNTAX_URL}/${SYNF_VIM} --output-document=${SD_DIR}/.${SYNF_VIM}
-
-  # removes existing slackdoc syntax template lines if they exist
-  sed -i /${FILETYPE}/d ${VIMRC}
-
-  # Write the new lines to the vimrc file
-  echo "\" Add a pointer to the ${FILETYPE} vim syntax file">>${VIMRC}
-  echo "au BufRead,BufNewFile *.${EXTENSION} set
-filetype=${FILETYPE}">>${VIMRC}
-  echo "au! Syntax ${FILETYPE} source ${SD_DIR}/.${SYNF_VIM}">>${VIMRC}
-
-  PrintText 2 "${SCSTXT}" "The script has added the following lines to your
-vimrc file" 1
-  cat ${VIMRC} | grep ${FILETYPE}
-  printf "\n"
-}
-
-KateSyntax() {
-  PrintText 2 "${BLDTXT}" \
-          "To implement syntax highlighting to slackdoc articles in kate you
-need to enable the MediaWiki syntax highlighting by going to Tools ->
-Highlighting -> Markup -> Mediawiki." 1
-}
-
 RunFunctions() {
   if [ -n "${FETCHSYNTAX}" ]; then # confirmed
     GetSyntaxExample
@@ -701,8 +735,7 @@ RunFunctions() {
   #NEWFILE
 
   if [ -n "${GETUPDATE}" ]; then
-  #  CheckUpdate
-    echo "Check for an update"
+    CheckUpdate
   fi
 }
 
